### ISSUE TITLE
Database \

### ISSUE THREAD

**Issue by kashifiqbal18099** [Farhan-Haseeb/wpf-school-management-system#1]
Database file is missing ? need database file for store procedures

**Comment by Farhan-Haseeb** [comment]
Uploaded the file. 
Not using Transactions so the DB will create issues in future need to implement those.

**Comment by kashifiqbal18099** [comment]
i just need .sql script to generate db with store procedures can you provide me ... ?

**Comment by Farhan-Haseeb** [comment]
I created the file in master [here](https://github.com/Farhan-Haseeb/wpf-school-management-system/blob/master/db)

**Comment by kashifiqbal18099** [comment]
thanks a lot
